# Changes here will be overwritten by Copier
_commit: 643d329
_src_path: .
editorconfig: true
hadolint: true
markdownlint: true
prettier: true
ruff: true
shellcheck: true
shfmt: true
typos: true
yamllint: true

