# Changes here will be overwritten by Copier
_commit: 2025.3.0-56-g7c1a46e
_src_path: .
conventional_commits: true
docker: false
editorconfig: true
markdown: true
prettier: true
python: true
shell: false
typos: true
yaml: true
