# Changes here will be overwritten by Copier
_commit: 2024.5.2
_src_path: .
editorconfig: true
hadolint: false
markdownlint: true
prettier: true
ruff: true
shellcheck: false
shfmt: false
typos: true
yamllint: true

