"""Jinja globals that seed copier answers from an existing project's layout.

Copier renders question defaults with the template's Jinja environment, so registering these helpers as globals
lets `copier.yaml` adopt whichever hook runner and web formatter a repository already uses instead of imposing
the template's preference on an established project. Answers are then recorded in `.copier-answers.yaml`, so
detection only runs the first time a project is templated.

Every helper falls back to the template's preferred tool and swallows filesystem errors: an exception raised
while rendering a question default aborts the whole survey.
"""

from __future__ import annotations

import json
from pathlib import Path
import re
from shutil import which
from typing import Any

from jinja2 import Environment
from jinja2.ext import Extension

# What this template recommends when a project shows no existing preference.
PREFERRED_HOOK_RUNNER = "prek"
PREFERRED_WEB_FORMAT_TOOL = "biome"

_HOOK_RUNNERS = ("prek", "pre-commit")

# Read caps keep detection cheap on repos with large configs or vendored files.
_MAX_READ_BYTES = 64 * 1024

# Both runners stamp their name into the git shims they install.
_PREK_SHIM = re.compile(r"generated by prek", re.IGNORECASE)
_PRE_COMMIT_SHIM = re.compile(r"generated by pre-commit", re.IGNORECASE)

# "pre-commit" is a substring of ".pre-commit-config.yaml", which prek also reads, so CI detection has to match
# the runner's own invocations rather than the config file name.
_PREK_USAGE = re.compile(r"(?<![\w./-])prek(?![\w-])")
_PRE_COMMIT_USAGE = re.compile(
    r"pre-commit/action|pre-commit-ci|pre-commit\.ci|(?<![\w./-])pre-commit\s+(?:run|install|autoupdate)"
)

# Hook types this template installs, plus the remaining ones either runner may have installed previously.
_HOOK_TYPES = (
    "pre-commit",
    "commit-msg",
    "pre-push",
    "post-checkout",
    "post-merge",
    "post-rewrite",
    "prepare-commit-msg",
    "pre-merge-commit",
    "pre-rebase",
    "post-commit",
)

_GIT_DIR_POINTER = re.compile(r"\s*gitdir:\s*(.+)")
_GIT_HOOKS_PATH = re.compile(r"^\s*hooksPath\s*=\s*(.+?)\s*$", re.MULTILINE)

# Biome discovers all four spellings, so all four are evidence that a project uses it.
_BIOME_CONFIGS = (".biome.json", ".biome.jsonc", "biome.json", "biome.jsonc")
_PRETTIER_CONFIGS = (
    ".prettierrc",
    ".prettierrc.cjs",
    ".prettierrc.js",
    ".prettierrc.json",
    ".prettierrc.json5",
    ".prettierrc.jsonc",
    ".prettierrc.mjs",
    ".prettierrc.toml",
    ".prettierrc.yaml",
    ".prettierrc.yml",
    ".prettierignore",
    "prettier.config.cjs",
    "prettier.config.js",
    "prettier.config.mjs",
    "prettier.config.ts",
)

_BIOME_HOOK = re.compile(r"biomejs/pre-commit|id:\s*[\"']?biome")
_PRETTIER_HOOK = re.compile(r"mirrors-prettier|id:\s*[\"']?prettier")

_BIOME_PACKAGE = "@biomejs/biome"
_PRETTIER_PACKAGE = "prettier"

_CI_GLOBS = (".github/workflows/*.yaml", ".github/workflows/*.yml")
_CI_FILES = (".gitlab-ci.yaml", ".gitlab-ci.yml", "azure-pipelines.yaml", "azure-pipelines.yml")

_PRE_COMMIT_CONFIGS = (".pre-commit-config.yaml", ".pre-commit-config.yml")


def _read_text(path: Path) -> str:
    """Return the head of `path`, or an empty string when it is missing or unreadable."""
    try:
        if not path.is_file():
            return ""
        with path.open("r", encoding="utf-8", errors="replace") as handle:
            return handle.read(_MAX_READ_BYTES)
    except OSError:
        return ""


def _resolve(root: Path, raw: str) -> Path:
    """Resolve a possibly relative path recorded in git metadata against `root`."""
    path = Path(raw.strip()).expanduser()
    return path if path.is_absolute() else root / path


def _git_dir(root: Path) -> Path | None:
    """Return `root`'s git directory, following the `gitdir:` pointer file used by worktrees and submodules."""
    candidate = root / ".git"
    if candidate.is_dir():
        return candidate
    match = _GIT_DIR_POINTER.match(_read_text(candidate))
    if match is None:
        return None
    pointer = _resolve(root, match.group(1))
    return pointer if pointer.is_dir() else None


def _hooks_dir(root: Path) -> Path | None:
    """Return the directory git actually runs hooks from, honoring a configured `core.hooksPath`."""
    git_dir = _git_dir(root)
    if git_dir is None:
        return None
    match = _GIT_HOOKS_PATH.search(_read_text(git_dir / "config"))
    if match is not None:
        return _resolve(root, match.group(1))
    return git_dir / "hooks"


def _pick(candidates: set[str], preferred: str) -> str | None:
    """Collapse detection results, favoring `preferred` when a project shows traces of both tools."""
    if not candidates:
        return None
    return preferred if preferred in candidates else next(iter(sorted(candidates)))


def _shim_runner(root: Path) -> str | None:
    """Identify the runner from the git hook shims currently installed."""
    hooks_dir = _hooks_dir(root)
    if hooks_dir is None:
        return None
    found: set[str] = set()
    for hook_type in _HOOK_TYPES:
        shim = _read_text(hooks_dir / hook_type)
        if _PREK_SHIM.search(shim):
            found.add("prek")
        elif _PRE_COMMIT_SHIM.search(shim):
            found.add("pre-commit")
    return _pick(found, PREFERRED_HOOK_RUNNER)


def _ci_files(root: Path) -> list[Path]:
    paths = [path for glob in _CI_GLOBS for path in sorted(root.glob(glob))]
    paths.extend(root / name for name in _CI_FILES)
    return paths


def _ci_runner(root: Path) -> str | None:
    """Identify the runner from how CI pipelines invoke it."""
    found: set[str] = set()
    for path in _ci_files(root):
        text = _read_text(path)
        if _PREK_USAGE.search(text):
            found.add("prek")
        if _PRE_COMMIT_USAGE.search(text):
            found.add("pre-commit")
    return _pick(found, PREFERRED_HOOK_RUNNER)


def _available_runner() -> str | None:
    """Identify the runner from what is actually installed on `PATH`."""
    return _pick({runner for runner in _HOOK_RUNNERS if which(runner)}, PREFERRED_HOOK_RUNNER)


def detect_hook_runner(dst_path: Any) -> str:
    """Return the hook runner the project at `dst_path` already uses, else the preferred one."""
    root = Path(str(dst_path))
    try:
        # prek.toml is prek-only; the pre-commit config is shared and says nothing about the runner.
        if (root / "prek.toml").is_file() or (root / ".prek.toml").is_file():
            return "prek"
        # Repo state is evidence about this project; PATH is only a tiebreak for when the repo is silent,
        # so that someone who has just `pre-commit` installed isn't handed prek instructions.
        for detector in (_shim_runner, _ci_runner, lambda _root: _available_runner()):
            runner = detector(root)
            if runner is not None:
                return runner
    except OSError:
        pass
    return PREFERRED_HOOK_RUNNER


def _hooked_web_format_tool(root: Path) -> str | None:
    """Identify the formatter from a pre-commit config this template rendered previously."""
    found: set[str] = set()
    for name in _PRE_COMMIT_CONFIGS:
        text = _read_text(root / name)
        if _BIOME_HOOK.search(text):
            found.add("biome")
        if _PRETTIER_HOOK.search(text):
            found.add("prettier")
    return _pick(found, PREFERRED_WEB_FORMAT_TOOL)


def _configured_web_format_tool(root: Path) -> str | None:
    """Identify the formatter from its own config files."""
    found: set[str] = set()
    if any((root / name).is_file() for name in _BIOME_CONFIGS):
        found.add("biome")
    if any((root / name).is_file() for name in _PRETTIER_CONFIGS):
        found.add("prettier")
    return _pick(found, PREFERRED_WEB_FORMAT_TOOL)


def _packaged_web_format_tool(root: Path) -> str | None:
    """Identify the formatter from package.json dependencies."""
    try:
        manifest = json.loads(_read_text(root / "package.json") or "{}")
    except ValueError:
        return None
    if not isinstance(manifest, dict):
        return None
    declared: set[str] = set()
    for field in ("dependencies", "devDependencies", "peerDependencies", "optionalDependencies"):
        section = manifest.get(field)
        if isinstance(section, dict):
            declared.update(section)
    found: set[str] = set()
    if _BIOME_PACKAGE in declared:
        found.add("biome")
    if _PRETTIER_PACKAGE in declared:
        found.add("prettier")
    return _pick(found, PREFERRED_WEB_FORMAT_TOOL)


def detect_web_format_tool(dst_path: Any) -> str:
    """Return the web formatter the project at `dst_path` already uses, else the preferred one."""
    root = Path(str(dst_path))
    try:
        for detector in (_hooked_web_format_tool, _configured_web_format_tool, _packaged_web_format_tool):
            tool = detector(root)
            if tool is not None:
                return tool
    except OSError:
        pass
    return PREFERRED_WEB_FORMAT_TOOL


class DetectExtension(Extension):
    """Expose the detection helpers as Jinja globals so `copier.yaml` can use them in question defaults."""

    def __init__(self, environment: Environment) -> None:
        super().__init__(environment)
        environment.globals["detect_hook_runner"] = detect_hook_runner
        environment.globals["detect_web_format_tool"] = detect_web_format_tool
